Repository 3scale-sre/prometheus-exporter-operator, pull requests merged in 2024-11, with the labels that each got.

#55 Update grafana-operator label selector from all examples to match default operator value
  config/samples/monitoring_v1alpha1_prometheusexporter.yaml
  docs/prometheus-exporter-crd-reference.md
  examples/cloudwatch/cloudwatch-cr.yaml
  examples/elasticsearch/es-cr.yaml
  examples/manticore/manticore-cr.yaml
  examples/memcached/memcached-cr.yaml
  examples/mysql/mysql-cr.yaml
  examples/postgresql/postgresql-cr.yaml
  examples/probe/probe-cr.yaml
  examples/redis/redis-cr-2.yaml
  examples/redis/redis-cr.yaml
  examples/sendgrid/sendgrid-cr.yaml
  examples/sphinx/sphinx-cr.yaml
  test/e2e/prometheusexporter-grafanadashboard-apiversion/01-prometheusexporter.yaml
  test/e2e/prometheusexporter/01-prometheusexporter.yaml
Labels: lgtm, approved, priority/important-soon, kind/documentation, size/S

#58 feat: new gh actions workflows
  .github/workflows/release-catalog.yaml
  .github/workflows/release.yaml
  Makefile
  README.md
  docs/release.md
Labels: lgtm, approved, size/M, kind/feature, priority/important-soon

#59 feat: customizable tolerations
  Makefile
  bundle/manifests/monitoring.3scale.net_prometheusexporters.yaml
  bundle/manifests/prometheus-exporter-operator.clusterserviceversion.yaml
  catalog/prometheus-exporter-operator/alpha-channel.yaml
  catalog/prometheus-exporter-operator/objects/prometheus-exporter-operator.v0.8.2-alpha.1.clusterserviceversion.yaml
  config/crd/bases/monitoring.3scale.net_prometheusexporters.yaml
  config/manager/kustomization.yaml
  docs/prometheus-exporter-crd-reference.md
  roles/prometheusexporter/templates/deployment.yml.j2
Labels: lgtm, approved, kind/feature, size/L, priority/important-soon

#60 feat: update exporters
  .gitignore
  Makefile
  bundle/manifests/prometheus-exporter-operator.clusterserviceversion.yaml
  catalog/prometheus-exporter-operator/alpha-channel.yaml
  catalog/prometheus-exporter-operator/objects/prometheus-exporter-operator.v0.8.2-alpha.2.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  examples/README.md
  roles/prometheusexporter/exporters/cloudwatch/vars.yml
  roles/prometheusexporter/exporters/es/container.yml.j2
  roles/prometheusexporter/exporters/es/vars.yml
  roles/prometheusexporter/exporters/manticore/vars.yml
  roles/prometheusexporter/exporters/memcached/vars.yml
  roles/prometheusexporter/exporters/mysql/vars.yml
  roles/prometheusexporter/exporters/postgresql/vars.yml
  roles/prometheusexporter/exporters/probe/vars.yml
  roles/prometheusexporter/exporters/redis/vars.yml
  roles/prometheusexporter/exporters/sendgrid/vars.yml
  roles/prometheusexporter/exporters/sphinx/vars.yml
Labels: lgtm, approved, size/M, kind/feature, priority/important-soon

#63 fix: add missing step in the release-catalog workflow
  .github/workflows/release-catalog.yaml
Labels: lgtm, approved, kind/feature, size/XS, priority/important-soon

#64 release: 0.8.2-alpha.3
  Makefile
  bundle/manifests/prometheus-exporter-operator.clusterserviceversion.yaml
  catalog/prometheus-exporter-operator/alpha-channel.yaml
  catalog/prometheus-exporter-operator/objects/prometheus-exporter-operator.v0.8.2-alpha.3.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  examples/README.md
  prometheus-rules/es-prometheusrule.yaml
  roles/prometheusexporter/exporters/es/grafanadashboard.json.j2
Labels: lgtm, approved, size/M, priority/important-soon, kind/bug, kind/documentation

#65 release: 0.8.2
  Makefile
  bundle.Dockerfile
  bundle/manifests/prometheus-exporter-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
Labels: lgtm, approved, priority/important-soon, size/S, kind/release

#67 clean: removes the stable check from the catalog workflow
  .github/workflows/release-catalog.yaml
Labels: lgtm, approved, priority/important-soon, kind/cleanup, size/S
